# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.cache/wt [current_project]
set_property parent.project_path C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.0 [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/ctrl_encode_def.v
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/EXT.v
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/IR.v
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/NPC.v
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/PC.v
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/RF.v
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/alu.v
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/instruction_def.v
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/ctrl.v
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/dm_4k.v
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/flopr.v
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/im_4k.v
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/mux.v
  C:/Users/lenovo/Desktop/P15_Final/P15_Final/P15_Final.srcs/sources_1/new/mips.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top mips -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mips.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mips_utilization_synth.rpt -pb mips_utilization_synth.pb"
